### ISSUE TITLE
2D Array Syntax Not Supported

### ISSUE THREAD

**Issue by sunjay** [0x8890/docchi#13]
I filed a [similar issue with doctrine](https://github.com/Constellation/doctrine/issues/108), but docchi doesn't seem to support 2D arrays either. JSDoc supports them and I've asked doctrine if they'll add support. It would be nice to have it here too because all my code is ES6.

Here's a valid docstring:

    /**
     * @param {Number[]} test
     */

Here's an invalid docstring according to docchi:

    /**
     * @param {Number[][]} test
     */

**Comment by daliwali** [comment]
This issue should probably be handled upstream at doctrine.
