### ISSUE TITLE
Support files that use babel's experimental es7

### ISSUE THREAD

**Issue by rolandpoulter** [0x8890/docchi#14]
I'm trying to use docchi to generate documentation for code that uses babel's experimental es7 syntax.
http://babeljs.io/docs/usage/experimental/

In my case I've got code that makes use of decorators. This is where it fails to parse:
```
Uncaught (in promise) SyntaxError: Unexpected character '@' (22:0)
    at Parser.8.pp.raise (http://localhost:3000/bundle/handbook.js:13493:15)
    at Parser.16.pp.getTokenFromCode (http://localhost:3000/bundle/handbook.js:15234:10)
    at Parser.16.pp.readToken (http://localhost:3000/bundle/handbook.js:14937:17)
    at Parser.16.pp.nextToken (http://localhost:3000/bundle/handbook.js:14929:73)
    at Parser.16.pp.next (http://localhost:3000/bundle/handbook.js:14878:10)
    at Parser.12.pp.eat (http://localhost:3000/bundle/handbook.js:13949:12)
    at Parser.12.pp.semicolon (http://localhost:3000/bundle/handbook.js:13991:15)
    at Parser.14.pp.parseVarStatement (http://localhost:3000/bundle/handbook.js:14386:10)
    at Parser.14.pp.parseStatement (http://localhost:3000/bundle/handbook.js:14185:21)
    at Parser.14.pp.parseTopLevel (http://localhost:3000/bundle/handbook.js:14127:23)
8.pp.raise @ acorn.js:1745
16.pp.getTokenFromCode @ acorn.js:3486
16.pp.readToken @ acorn.js:3189
16.pp.nextToken @ acorn.js:3181
16.pp.next @ acorn.js:3130
12.pp.eat @ acorn.js:2201
12.pp.semicolon @ acorn.js:2243
14.pp.parseVarStatement @ acorn.js:2638
14.pp.parseStatement @ acorn.js:2437
14.pp.parseTopLevel @ acorn.js:2379
parse @ acorn.js:101
Docchi @ index.js:72
parse @ index.js:160
(anonymous function) @ HomePage.js:50
```

Is this something you intend to support in the future?

**Comment by rolandpoulter** [comment]
I'm guessing this is more of an issue with acorn than docchi.

**Comment by daliwali** [comment]
@rolandpoulter yup, it's an acorn issue. I'd like to support ES7, but first it must be supported in acorn. in the meanwhile, perhaps it could fallback to acorn's [`parse_dammit`](https://github.com/marijnh/acorn/blob/master/src/loose/index.js).

**Comment by djMax** [comment]
https://github.com/ternjs/acorn/issues/309

Does this mean we can support it now somehow? I need it for an open source project we're about to launch that uses Docchi. We avoid async/await right now, but this would force everyone else to do so too which I didn't want to do...

**Comment by 0x8890** [comment]
It looks like this should work already, by passing `plugins` to acorn.

```js
docchi.parse(code, {
  plugins: [ ... ]
})
```

Though I haven't tried it yet.

**Comment by djMax** [comment]
sorta kinda. I was going to make a PR because the problem now is that in complex projects, I don't see exactly how to install the plugin. As you say, this works:

```
const acorn = require('acorn');
require('acorn-es7-plugin')(acorn);
  let doc = docchi.parse(readFile('fixtures/fixture1.js'), {ecmaVersion: 7, plugins:{asyncawait:true}})
```

But, when I do that in my module that contains docchi, the acorn I get is not the one docchi uses because "life," and that's probably not the cleanest way to inject the plugin anyways. It doesn't seem like I can inject the acorn-es7-plugin directy via options. So perhaps I could expose the acorn instance that docchi uses upwards?

**Comment by 0x8890** [comment]
Exposing the `acorn` instance sounds OK to me. PR welcome.

**Comment by djMax** [comment]
#17

**Comment by 0x8890** [comment]
This should be resolved now.
